studyproject/forthapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('C/', views.c, name='C'),
    path('R/', views.r, name='R1'),
    path('R/<int:id>/', views.r, name='R2'),
    path('U/<int:id>/', views.u, name='U'),
    path('D/<int:id>/', views.d, name='D'),
]

studyproject/studyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import firstapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/', firstapp.views.welcome),
    path('secondapp/', include('secondapp.urls')),
    path('forthapp/', include('forthapp.urls')),
    path('uploadapp/', include('uploadapp.urls')),
    path('townmanager/', include('townmanager.urls')),
    path('relationapp/', include('relationapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyproject/townmanager/urls.py
from django.conf import settings
# from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'townmanager'
urlpatterns = [
    path('', views.townmanager_index, name = 'townmanager_index'),
    path('myPage', views.myPage, name = 'myPage'),
    path('job_intro', views.job_intro, name = 'job_intro'),
    path('login', views.login, name = 'login'),

    path('index', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),

]

studyproject/townmanager/models.py
from django.db import models

studyproject/townmanager/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect
import random
from datetime import datetime
from django.http import JsonResponse

from django.contrib.auth.models import User
from django.contrib import auth

from django.views.generic import ListView, TemplateView

import townmanager





def townmanager_index(request):
    context = None
    if request.user.is_authenticated:
        context = {'logineduser': request.user.last_name+request.user.first_name}
    return render(request, 'townmanager_index.html', context)

def myPage(request):
    context = None
    if request.user.is_authenticated:
        context = {'logineduser': request.user.last_name+request.user.first_name, 'email': request.user.username, 'birth': str(request.user.date_joined)[:10], 'place': request.user.email}
    return render(request, 'myPage.html', context)

def login(request):
    return render(request, 'login.html')

def job_intro(request):
    context = None
    if request.user.is_authenticated:
        context = {'logineduser': request.user.last_name+request.user.first_name}
    return render(request, 'job_intro.html', context)



def index(request) :
    context = None
    print(request.user.is_authenticated)
    print(request.user)
    if request.user.is_authenticated:
        context = {'logineduser': request.user}
    return render(request, 'index.html', context)

def register(request):
    res_data = None
    if request.method =='POST':
        useremail = request.POST.get('useremail')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        password = request.POST.get('password')
        re_password = request.POST.get('re-password')
        birth = request.POST.get('birth')
        place = request.POST.get('place')
        res_data = {}
        if User.objects.filter(username=useremail):
            res_data['error']='이미 가입된 아이디(이메일주소)입니다.'
        elif password != re_password:
            res_data['error']='비밀번호가 다릅니다.'
        else:
            user = User.objects.create_user(username = useremail,
                            first_name = firstname,
                            last_name = lastname,
                            password = password,
                            date_joined = birth,
                            email = place,
                            )
            auth.login(request, user)
            return redirect("townmanager:townmanager_index")
    return render(request, 'register.html', res_data)


def login(request):
    if request.method == "POST":
        useremail = request.POST.get('useremail', None)
        password = request.POST.get('password', None)
        user = auth.authenticate(username=useremail, password=password)
        #print("***", user.date_joined)
        if user is not None :
            auth.login(request, user)
            return redirect("townmanager:townmanager_index")
        else :
            return render(request, 'login.html', {'error': '사용자 아이디 또는 패스워드가 틀립니다.'})
    else :
        return render(request, 'login.html')

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
    return redirect("townmanager:townmanager_index")

studyproject/townmanager/templates/index.html
{% extends "base.html" %}
{% block content %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul>
     <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Dropdown link
      </a>
      <div class="dropdown-menu">
        {% if not logineduser %}
            <a class="dropdown-item" href="{% url 'townmanager:register' %}">회원가입</a>
            <a class="dropdown-item" href="{% url 'townmanager:login' %}">로그인</a>
        {% else %}
            <a class="dropdown-item" href="{% url 'townmanager:logout' %}">로그아웃</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'townmanager:myPage' %}">회원페이지</a>
      </div>
    </li>
  </ul>
</nav>
{% endblock %}

studyproject/townmanager/templates/login.html
{% extends "base.html" %}
{% block content %}
{% if msg  %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>{{msg}}</h1>
        </div>
    </div>
{% else %}

    <section class="vh-100" style="background-color: #212529;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                    <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://img.freepik.com/free-photo/successful-business-team-expressing-unity_74855-1638.jpg?w=740&t=st=1664871868~exp=1664872468~hmac=f6c43a793aaad68aba4b68eb1e49b99182dc8dd146c52916e8404c851ae328ca"
                        alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                    </div>
                    <div class="col-md-6 col-lg-7 d-flex align-items-center">

                        {% load static %}
                        <div class="card-body p-4 p-lg-5 text-black">  
                            <span class="mb-0">
                                <a class="navbar-brand" href="./">
                                    <img src = "{% static 'img/logo_long.png' %}" style = 'max-height: 40px; width: auto'>
                                </a>
                            </span><br><br>

                            <form method="POST" action="{% url 'townmanager:login'%}">
                                {% csrf_token %}
                                <div class="d-flex align-items-center my-3 mb-0 pb-0">
                                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                </div>

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="username">이메일</label>
                                    <input type="text" name="useremail" id="form2Example17" class="form-control form-control-lg" placeholder="사용자 아이디" required/>
                                </div>
                
                                <div class="form-outline mb-4">
                                    <label class="form-label" for="password">비밀번호</label>
                                    <input type="password" name="password" id="form2Example27" class="form-control form-control-lg" placeholder="비밀번호" required/>
                                </div>

                                <div class="row mb-2 mt-2">
                                    <div class="col-12 text-left" style="color:red">
                                     {{error}}
                                    </div>
                                </div>

                                <div class="pt-1 mb-4">
                                    <button class="btn btn-dark btn-lg btn-block" style="width:100px;" type="submit">로그인</button>
                                </div>

                                <div class="form-outline mb-4" style = "font-size: large;">
                                    <a class="small text-muted" href="#!">비밀번호 찾기</a><br>
                                    <p class="mb-5 pb-lg-2" style="color: #393f81;">아직 계정이 없으신가요? <a href="{% url 'townmanager:register' %}"
                                        style="color: #393f81;">지금 바로 회원가입</a></p><br>
                                    <a href="https://docs.google.com/document/d/e/2PACX-1vQnQNlxWc5Crsc3W2dKR0FXOcoFblWyqI4dwRaKhpCCUIxDSM8IhRu-KK09qQwBmPHB6zKgorSI_fym/pub" class="small text-muted" style = "margin-right: 10px;">이용약관</a>
                                    <a href="https://docs.google.com/document/d/e/2PACX-1vQB3jvrh1h59MECkdwRZF37S4I5udr_l4PjEtksllN8NgPmSED-eNu9nDxkAa1R0gAXg8KeSDHKeyZO/pub" class="small text-muted">개인정보 보호 정책</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </section>
{% endif %}
    <div class="col-12 text-center">
        <a href="{% url 'townmanager:index' %}">메인화면으로</a>
    </div>
{% endblock %}



<!-- <!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>TownManager | 주거 및 환경 관리 전문가 구직 플랫폼</title>
        <link rel="icon" href="{% static 'img/TownManager.png' %}" sizes="32x32"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <section class="vh-100" style="background-color: #212529;">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-10">
                    <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                        <img src="https://img.freepik.com/free-photo/successful-business-team-expressing-unity_74855-1638.jpg?w=740&t=st=1664871868~exp=1664872468~hmac=f6c43a793aaad68aba4b68eb1e49b99182dc8dd146c52916e8404c851ae328ca"
                            alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">

                            <div class="card-body p-4 p-lg-5 text-black">  
                                <span class="mb-0">
                                    <img src = "{% static 'img/logo_long.png' %}" style = 'max-height: 40px; width: auto' href = "townmanager_index">
                                </span><br><br>

                                <form method="POST" action="{% url 'townmanager:login'%}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="username">사용자 아이디</label>
                                       <input type="text" class="form-control"  name="useremail" placeholder="사용자 아이디" >
                                    </div>
                                      <div class="form-group">
                                         <label for="password">비밀번호</label>
                                         <input type="password" class="form-control" name="password" placeholder="비밀번호" >
                                      </div>
                                      <button type="submit" class="btn btn-primary">로그인</button>
                                  </form>

                                <form>
                                    <div class="d-flex align-items-center my-3 mb-0 pb-0">
                                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form2Example17">이메일</label>
                                        <input type="email" id="form2Example17" class="form-control form-control-lg" required/>
                                    </div>
                    
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form2Example27">비밀번호</label>
                                        <input type="password" id="form2Example27" class="form-control form-control-lg" required/>
                                    </div>
                    
                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-dark btn-lg btn-block" type="button">로그인</button>
                                    </div>
                                    <div class="form-outline mb-4" style = "font-size: large;">
                                        <a class="small text-muted" href="#!">비밀번호 찾기</a><br>
                                        <p class="mb-5 pb-lg-2" style="color: #393f81;">아직 계정이 없으신가요? <a href="#!"
                                            style="color: #393f81;">지금 바로 회원가입</a></p><br>
                                        <a href="https://docs.google.com/document/d/e/2PACX-1vQnQNlxWc5Crsc3W2dKR0FXOcoFblWyqI4dwRaKhpCCUIxDSM8IhRu-KK09qQwBmPHB6zKgorSI_fym/pub" class="small text-muted" style = "margin-right: 10px;">이용약관</a>
                                        <a href="https://docs.google.com/document/d/e/2PACX-1vQB3jvrh1h59MECkdwRZF37S4I5udr_l4PjEtksllN8NgPmSED-eNu9nDxkAa1R0gAXg8KeSDHKeyZO/pub" class="small text-muted">개인정보 보호 정책</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </section>
    </body>
</html>
 -->

studyproject/townmanager/templates/logout.html
{% extends "base.html" %}
{% block content %}
<div class="row mt-5">
    <div class="col-12 text-center" style="color:green">
        <h1>{{ msg }}</h1>
    </div>
</div>
<div class="col-12 text-center">
        <a href="{% url 'townmanager:townmanager_index' %}">메인화면으로</a>
</div>
{% endblock %}

studyproject/townmanager/templates/myPage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>TownManager | 주거 및 환경 관리 전문가 구직 플랫폼</title>
        <link rel="icon" href="{% static 'img/TownManager.png' %}" sizes="32x32"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="./">
                    <img src = "{% static 'img/logo_long.png' %}" style = 'max-height: 40px; width: auto'>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item dropdown" style = "font-weight: bold;">
                            <a class="nav-link dropdown-toggle" style="margin-right: 40px;" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">직군별 찾아보기</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" style = "font-weight: bold;" href="#!">직군전체</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">관리</a></li>
                                <li><a class="dropdown-item" href="#!">기계</a></li>
                                <li><a class="dropdown-item" href="#!">소방</a></li>
                                <li><a class="dropdown-item" href="#!">전기</a></li>
                                <li><a class="dropdown-item" href="#!">영선</a></li>
                                <li><a class="dropdown-item" href="#!">미화</a></li>
                                <li><a class="dropdown-item" href="#!">경리</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#!" id = 'drawer-opener' style = "font-weight: bold;">플랫폼소개</a>
                        </li>
                        <div class = 'drawer' style="z-index: 10; margin-top: 10px; margin-bottom: 10px; border-top-left-radius: 20px; border-bottom-left-radius: 20px;">
                            <h2 style="text-align:center;">플랫폼소개</h2>
                            <hr>
                            <ul class="px-4 px-lg-4 my-4">
                                <li style="font-size:large">2021년 경비직을 비롯한 시설관리직군은 150만회에 달하는 계약이 체결되었습니다. 그러나 기존 채용 방식은 인맥 위주 채용, 등록 회비를 부과하는 협회 주도의 독점이 되고 있습니다.</li>
                                <br>
                                <li style="font-size:large">이에 해당 분야에서 사용자가 자신의 전문분야를 등록하고 적합한 공고를 무료로 찾아볼 수 있는 플랫폼을 만들었습니다.</li>
                                <br>
                                <li style="font-size:large">사용자와 구직자가 서로를 효율적으로 이어줄 수 있도록 타운매니저가 돕겠습니다.</li>
                                <br>
                                <button class="btn btn-outline-dark" id = 'drawer-opener-in-sideMenu' type="button">
                                    <i class="bi-backspace-fill me-1" ></i>
                                    뒤로가기
                                </button>
                            </ul>
                        </div>
            
                        <script src="{% static 'js/sidemenu.js' %}"></script>
                    </ul>
                    <form class="d-flex">

                        {% if not logineduser %}
                        <a class="nav-link active" aria-current="page" href="login">로그인</a>
                        {% else %}
                        <a class="d-flex align-items-center text-black text-decoration-none">환영합니다 {{ logineduser }}님!</a>
                        <a class="nav-link active" aria-current="page" href="{% url 'townmanager:logout' %}">로그아웃</a>
                        
                        <button type = "button" class="btn btn-outline-dark" onclick="location.href='myPage'">
                            <i class="bi-flag-fill me-1"></i>
                            마이페이지
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </nav>
        <header class="bg-dark py-2 border-bottom mb-4">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">마이페이지</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{{ logineduser }}님께 딱 맞는 추천 공고</p>
                </div>
            </div>
        </header>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">나의 정보</h2>
                            <div class="small text-muted">{78}일 전 수정
                                <a class="btn btn-outline-dark" style="float: right;" href="#!">정보 수정</a>
                            </div>
                            
                            <ul class="list-unstyled mb-0 mt-4">
                                <h5>이름</h5><li class="card-text">{{ logineduser }}</li><br>
                                <h5>주소</h5><li class="card-text">{{ place }}</li><br>
                                <h5>경력</h5><li class="card-text">XXXX코퍼레이션 (2017.08 ~ 2022.03)<br>
                                    빅데이터 수집 및 전처리<br>
                                    - 크롤링 프로그램 개발 라디오 플랫폼 음원 수집, 전처리<br>
                                    - 국공립 기관 공공데이터 수집 기획, 수행<br>
                                    - 다국어 텍스트 받아쓰기 인력 구인, 관리</li><br>
                                <h5>포지션</h5><li class="card-text">시설관리</li><br>
                                <h5>전화번호</h5><li class="card-text">010-1234-1234</li><br>
                                <h5>생년월일</h5><li class="card-text">{{ birth }}</li><br>
                                <h5>이메일</h5><li class="card-text">{{ email }}</li><br>
                            </ul>  
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-4 col-12 text-center">
                            <h3>{{ logineduser }}님을 위한 맞춤형 공고</h3>
                        </div>
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{% static 'img/금천구청.JPG' %}" alt="..." /></a>
                                <div class="card-body">
                                    <h2 class="card-title h4">금천구청</h2>
                                    <div class="mb-2 small text-muted">~2022-10-30</div>
                                    <p class="card-text" style="font-size:large">영선반장 채용</p>
                                    <a class="btn btn-primary" href="#!">상세보기</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{% static 'img/올림픽공원.JPG' %}" alt="..." /></a>
                                <div class="card-body">
                                    <h2 class="card-title h4">올림픽공원</h2>
                                    <div class="mb-2 small text-muted">~2022-11-06</div>
                                    <p class="card-text" style="font-size:large">시설관리 총괄 채용</p>
                                    <a class="btn btn-primary" href="#!">상세보기</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{% static 'img/종로타워.JPG' %}" alt="..." /></a>
                                <div class="card-body">
                                    <h2 class="card-title h4">종로타워</h2>
                                    <div class="mb-2 small text-muted">~2022-11-16</div>
                                    <p class="card-text" style="font-size:large">경리주임 채용</p>
                                    <a class="btn btn-primary" href="#!">상세보기</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{% static 'img/라마다호텔.JPG' %}" alt="..." /></a>
                                <div class="card-body">
                                    <h2 class="card-title h4">라마다호텔</h2>
                                    <div class="mb-2 small text-muted">~2022-10-28</div>
                                    <p class="card-text" style="font-size:large">전기과장 채용</p>
                                    <a class="btn btn-primary" href="#!">상세보기</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav> -->
                </div>

                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-header">프로필 사진</div>
                        <div class="card-body">
                            <a href="#!"><img class="card-img-top" src="{% static 'img/LeeJunmin.JPG' %}" style = "background-size: cover;" alt="..." /></a>
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">내가 찜한 공고</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <ul class="list-unstyled mb-0" style="margin-left: 20px; list-style-type: '👉 ';">
                                        <li><a href="{% url 'townmanager:job_intro' %}">[금천구청] 영선반장 채용</a></li>
                                        <li><a href="{% url 'townmanager:job_intro' %}">[종로타워] 경리주임 채용</a></li>
                                        <li><a href="{% url 'townmanager:job_intro' %}">[올림픽공원] 시설관리총괄 채용</a></li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <footer class="py-5 bg-dark">
            <div class = "text-center container" style="margin-bottom: 30px">
                <p class="text-center text-white" style="font-size: large; margin-right: 150px"><a class="m-0" href="#!">FAQ</a></p>
                <p class="text-center text-white" style="font-size: large;"><a class="m-0" href="#!">문의하기</a></p>
            </div><br>
            <div class="text-center container">
                <div class="container">
                    <div class="container"><li class="m-0 text-center text-white" style='list-style-type: none'>&copy; TownManager, Inc. 2022 All rights reserved.</li></div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>