studyproject/forthapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('C/', views.c, name='C'),
    path('R/', views.r, name='R1'),
    path('R/<int:id>/', views.r, name='R2'),
    path('U/<int:id>/', views.u, name='U'),
    path('D/<int:id>/', views.d, name='D'),
]

studyproject/studyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import firstapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/', firstapp.views.welcome),
    path('secondapp/', include('secondapp.urls')),
    path('forthapp/', include('forthapp.urls')),
    path('uploadapp/', include('uploadapp.urls')),
    path('townmanager/', include('townmanager.urls')),
    path('relationapp/', include('relationapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyproject/visitorapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("visitorC/", views.v_create, name="vC"),
    path("visitorR/", views.v_read, name="vR"),
    path("visitorU/", views.v_update, name="vU"),
    path("visitorD/", views.v_delete, name="vD"),
    path("replyC/", views.reply_create, name="rC"),
    path("replyR/", views.reply_read, name="rR"),
    path("search1/<name>", views.search1, name="search1"),
    path("search2/<content>", views.search2, name="search2"),
]

studyproject/visitorapp/models.py
from django.db import models

class Visitor(models.Model) :
    name = models.CharField(max_length=6)
    memo = models.TextField()
    writedate = models.DateTimeField(auto_now_add=True) # auto_now

    def __str__(self):
        return "main {}-{}-{}".format(self.id, self.name, self.memo)


class Reply(models.Model):
    content = models.CharField(max_length=80)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE)

    def __str__(self):
        return "replay {}-{}-{}".format(self.id, self.content, self.visitor_id)

studyproject/visitorapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import  JsonResponse
from .models import Visitor, Reply

def v_create(request) :
        name = request.POST['name']
        memo = request.POST['memo']
        vdata = Visitor(name=name, memo=memo)
        vdata.save()
        return redirect("vR")

def v_read(request) :
    page = request.GET.get('page', 1)
    vlist = Visitor.objects.all()
    paginator = Paginator(vlist, 3)
    #print(paginator)
    vlistpage = paginator.get_page(page)
    #print(type(vlistpage))
    #for d in vlistpage :
    #    print(type(d), d)
    context = {"vlist": vlistpage}
    return render(request, 'visitor_crud.html', context)

def v_update(request):
    if request.method == "POST" :
        pk = request.GET.get("pk")
        visitor = Visitor.objects.get(pk=pk)
        visitor.name = request.POST['name']
        visitor.memo = request.POST['memo']
        visitor.save()
        return redirect("vR")
    else :
        pk = request.GET.get("pk")
        visitor = Visitor.objects.get(pk=pk)
        jsonContent = {"name" : visitor.name, "memo": visitor.memo }
        return JsonResponse( jsonContent, json_dumps_params={'ensure_ascii':False})

def v_delete(request) :
    pk = request.GET['pk']
    visitor = Visitor.objects.get(pk=pk)
    visitor.delete()
    return redirect("vR")

def reply_create(request):
    content = request.GET['content']
    pk = request.GET['pk']
    visitor = Visitor.objects.get(pk=pk)  # pk=pk, id=pk
    rdata = Reply(content=content, visitor=visitor)
    rdata.save()
    return JsonResponse({"result":"success"})


def reply_read(request):
    pk = request.GET['pk']
    rlist = []
    reply = Reply.objects.filter(visitor=pk)
    for r in reply :
        print(r)
        rlist.append(r.content)
    if len(rlist) == 0 :
        rlist = ['힝~ 아직 소중한 댓글이 없어용']
    return JsonResponse({"result": rlist})

def search1(request, name) :
    page = request.GET.get('page', 1)
    vlist = Visitor.objects.filter(name = name)
    paginator = Paginator(vlist, 3)
    vlistpage = paginator.get_page(page)
    context = {"vlist": vlistpage}
    return render(request, 'visitor_crud.html', context)

def search2(request, content):
    page = request.GET.get('page', 1)
    vlist = Visitor.objects.filter(memo__contains=content)
    paginator = Paginator(vlist, 3)
    vlistpage = paginator.get_page(page)
    context = {"vlist": vlistpage}
    return render(request, 'visitor_crud.html', context)

studyproject/visitorapp/templates/visitor_crud.html
{% extends 'basesimple.html' %}

{% block mycontent %}
<h2><a href="{% url 'vR' %}">방명록에 남겨진 글들</a></h2>
<hr>
{% load static %}
<table>
{% for vdata in vlist %}
      <tr>
          <td>{{ vdata.name }}</td>
          <td>{{ vdata.memo }}<span onclick="read_reply({{ vdata.pk }})">({{vdata.reply_set.values|length}})</span></td>
          <td>{{ vdata.writedate }}</td>
          <td><img src="{% static  'images/delete.png' %}" onclick="dd_confirm('{{ vdata.name }}', {{ vdata.pk }})" width="20"></td>
          <td><img src="{% static  'images/edit.png' %}" onclick="ajax_uu_request({{ vdata.pk }})" width="20"></td>
          <td><img src="{% static  'images/reply.jpg' %}" onclick="write_reply({{ vdata.pk }})" width="20"></td>
      </tr>
{% endfor %}
</table>
<h5>
	{% if vlist.has_previous %}
		<a href='?page={{vlist.number|add:-1}}'>이전페이지</a>
	{% endif %}
	Page {{ vlist.number }} / {{ vlist.paginator.num_pages }}
	{% if vlist.has_next %}
		<a href='?page={{vlist.number|add:+1}}'>다음페이지</a>
	{% endif %}
</h5>
<div id="searchdiv">
    <select name="searchtype">
        <option value="search1">작성자명</option>
        <option value="search2">작성내용</option>
    </select>
    <input type="text" name="keyword">
    <button  onclick="processSearch() ">검색</button>
</div>
<div id="btndiv"><button  onclick="displayInputForm() ">글 작성하기</button></div>
<div id="ccform"  style="display:none">
  <h2>의견을 남겨 주세요!</h2>
	<hr>
	<form method="post" action="{% url 'vC' %}">
        {% csrf_token %}
		<input type="text" name="name"  placeholder="작성자 이름을 입력해 주세요"><br>
		<textarea style="margin-top:5px" name="memo" cols="60" rows="5" placeholder="자신의 의견을 간단히 적어주세요."></textarea>
 		</textarea><br>
 		<button type="submit">제출</button>
 		<button type="reset">재작성</button>
        <button onclick="">취소</button>
	</form>
</div>
<script>
    function displayInputForm() {
        document.getElementById('ccform').style.display = 'block';
    }
    function dd_confirm(name, pk) {
        let result = confirm(name+"님의 글을 삭제하겠습니까??");
        if( result )
            location.href = "{% url 'vD' %}?pk="+pk;
    }
    function ajax_uu_request(pk) {
        let xhr = new XMLHttpRequest();
        xhr.onload = function(){
            let jsonObj = JSON.parse(xhr.responseText);
            document.getElementById('ccform').style.display = 'block';
            const dom1 = document.querySelector('[name="name"]');
            const dom2 = document.querySelector('[name="memo"]');
            dom1.value = jsonObj.name;
            dom2.textContent = jsonObj.memo;
            document.querySelector('#ccform h2').textContent = "글을 수정해 주세요";
            document.querySelector('#ccform form').action = "{% url 'vU' %}?pk="+pk;
        };
        xhr.open("GET", "{% url 'vU' %}?pk="+pk, true);
        xhr.send();
    }
    function write_reply(pk) {
        const replycontent = window.prompt("댓글을 작성하세요");
        let xhr = new XMLHttpRequest();
        xhr.onload = function(){
            let jsonObj = JSON.parse(xhr.responseText);
            alert(jsonObj.result)
            location.href = "{% url 'vR' %}?page="+{{ vlist.number }};
        };
        xhr.open("GET", "{% url 'rC' %}?pk="+pk+"&content="+replycontent, true);
        xhr.send();
    }
    function read_reply(pk) {
        let xhr = new XMLHttpRequest();
        xhr.onload = function(){
            let jsonObj = JSON.parse(xhr.responseText);
            let msg = "";
            for (let i  in jsonObj.result)
                msg += jsonObj.result[i] +"\n";
            alert(msg)
        };
        xhr.open("GET", "{% url 'rR' %}?pk="+pk, true);
        xhr.send();
    }
    function processSearch() {
         location.href = '/visitorapp/'+document.querySelector('[name="searchtype"]').value+'/'+document.querySelector('[name="keyword"]').value;
    }
</script>
{% endblock %}

{% block mycss %}
  button {
    margin-top : 5px;
  }
  td {
    border-bottom : 1px dotted gray;
  }
  tr:hover {
    background-color : pink;
  }
  h2, h5 {
    text-align : center;
  }
#ccform, table {
    width:60%;
    margin-left : auto;
    margin-right : auto;
}
#btndiv, #searchdiv {
    text-align : center;
}
h2>img {
    width:30px;
}
a {
    text-decoration : none;
}
{% endblock %}